services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gym_instructor
    ports:
      - "5439:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
